
let config = {
  modules:[
    {name:'前端框架',to:'/Framework/0',children:[
      {
        name:'Juicy',
        class:'Red',
        to:'/Framework/Juicy',
        explain:'Juicy框架--独立应用的前端开发框架',
        detail:'Juicy框架是前端团队构建的用来进行s3独立页面应用的开发工作的一个框架，Juicy集成了工银聚团队开发必须的s3.js。',
      },
      {
        name:'S3',
        class:'pink',
        to:'/Framework/S3',
        explain:'S3--独立应用的前端开发框架',
        detail:'S3，Juicy集成了工银聚团队开发必须的s3.js。',
      }
    ]},
    {name:'控件库',to:'/Plugins/1',children:[
      {
        name:'111',
        class:'Red',
        to:'/Plugins/111',
        explain:'Juicy框架--22',
        detail:'，Juicy集成了工银聚团队开发必须的s3.js。',
      },
      {
        name:'333',
        class:'22',
        to:'/Plugins/22',
        explain:'S3--',
        detail:'S223.js。',
      }
    ]},
    {name:'PPT模板',to:'/ppt'},
    {name:'关于',to:'/About'},
  ]
};
